# Generated by Django 4.2.3 on 2023-07-27 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_uid_timingtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5270012b-805a-42b9-aa67-4e3a8c792452'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5270012b-805a-42b9-aa67-4e3a8c792452'), editable=False, primary_key=True, serialize=False),
        ),
    ]
