# Generated by Django 4.2.3 on 2023-07-27 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9201a059-f94d-4144-aa9b-6fa2361d740b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9201a059-f94d-4144-aa9b-6fa2361d740b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
