# Generated by Django 4.2.3 on 2023-07-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timingtodo',
            name='timing',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4fddde29-c799-4ab6-8a8f-c463a07361ca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4fddde29-c799-4ab6-8a8f-c463a07361ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
