# Generated by Django 4.2.3 on 2023-07-27 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cc30a52-e002-4024-ad0b-fbe24926a7e4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cc30a52-e002-4024-ad0b-fbe24926a7e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
