# Generated by Django 4.2.3 on 2023-07-27 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('22810f2d-8602-4430-b2d3-a7fd6c323dbb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('22810f2d-8602-4430-b2d3-a7fd6c323dbb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
